### ISSUE TITLE
Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by clunkcc** [MethosNL/TrellOps#3]
I have recently run into the following error:

Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure channel

My code has been working perfectly before, and now it has stopped working.
StackOverflow suggests that it is because it is the wrong TLS version. 
https://stackoverflow.com/questions/41618766/powershell-invoke-webrequest-fails-with-ssl-tls-secure-channel

Any ideas why this has started now?

**Comment by falkheiland** [comment]
same here

**Comment by clunkcc** [comment]
I did some more investigation:
It looks like [Trello removed TLS 1.0 support back in May](https://trello.com/c/8np6xdTH/16-removing-tls-10-support).
Powershell uses TLS 1.0 by default.
To fix the error and get powershell to use TLS 1.2, add the following line to your code:
`[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`
